[PipBoy]

# Allows treatment directly from the paper doll on the stats screen of the Pip-Boy.
# When using quick treatment, a preview box will show the treatment to be performed.
#
# 0 = Disable all interaction
# 1 = Vanilla, click body part to use Doctor's Bag to restore selected part (admittedly wasteful and useless)
# 2 = Click body part to open treatment menu
# 3 = Click body part to apply selected treatment directly (quick treatment)
#
# Default: 3
iPipBoyPaperDollTreatment = 3

# Show an information box about treatment when hovering over a paper doll body part.
# The preview box will show whether treatment is possible, skill requirements, and needed items.
#
# If disabled with quick treatment enabled, player might not know which items will be consumed.
#
# Default: 1
bPipBoyPaperDollTreatmentPreview = 1

# Modify what the "Doctor's Bag" button on the Pip-Boy stats screen does.
#
# 0 = Vanilla, consume bag and heal
# 1 = Open triage menu
#
# Default: 1
iPipBoyDoctorsBagBehavior = 1

# Modify what using a Doctor's Bag from the inventory, hotkey, or QuickSelect does.
#
# 0 = Vanilla, consume bag and heal
# 1 = Open triage menu
#
# Default: 0
iInventoryDoctorsBagBehavior = 1


[TriageMenu]

# Lists either all body parts or only parts with zero condition.
# Set to 1 to allow cheap restoration of non-crippled body parts.
# 
# 0 = Show every body part
# 1 = Show crippled body parts only
bShowOnlyCrippledBodyParts = 0

# Customize display of body part options in triage menu.
# Note that textual health description is shown on treatment menu as well.
# 
# 0 = Hide condition
# 1 = Description
# 2 = Percentage
# 3 = Description and percentage
#
# Default: 2
iShowBodyPartHealth = 2

# Emphasize crippled body-part conditions with asterisks.
#
# Default: 1
bShowBodyPartHealthEmphasis = 0

# Prefix body part options with skill requirements.
# Skill requirements may differ for body parts and their condition.
#
# 0 = Hide Medicine requirements (e.g. "Left Arm")
# 1 = Show required skill (e.g. "[Medicine 40] Left Arm")
# 2 = Show current and required skill (e.g. "[Medicine 35/40] Left Arm")
#
# Default: 1
iShowSkillRequirements = 1


[TreatmentMenu]

# Prefix treatment option item requirements with number held and needed (typically only one).
#
# 0 = Hide numbers (e.g. "[Medical Brace]")
# 1 = Show numbers only when requirements are not met (e.g. "[Medical Brace 0/1]")
# 2 = Always show number needed and held (e.g. "[Medical Brace 6/1]")
#
# Default: 0
iShowItemNumRequirements = 0


[Treatment]

# Maximum limb condition restored through treatment at maximum Medicine skill.
# Restoration scales with items used, the type of treatment, and the player's skill.
#
# Default: 0.85
fMaxRestoreFactor = 0.85

# Brings down the Pip-Boy and briefly fades to black with a sound when treating a crippled body part.
#
# Default: 1
bShowAnimationForMajorTreatment = 1

# Brings down the Pip-Boy and briefly fades to black with a sound when treating a non-crippled body part.
#
# Default: 0
bShowAnimationForMinorTreatment = 0

# The amount of health restored per limb for every hour slept.
# Only restores health of non-crippled limbs.
# Set to 0.0 to disable sleep healing.
#
# Default: 0.05
fSleepRestorationFactor = 0.05
