[General]

# Enables the triage and treatment menu when using a Doctor's Bag.
# 0 = Vanilla, using a Doctor's Bag uses it to restore body parts
# 1 = Using Doctor's Bag brings up the triage menu and allows advanced healing
#
# Default: 1
bEnableTriage = 1


[TriageMenu]

# Lists either all body parts or only parts with zero condition.
# Set to 1 to allow cheap restoration of non-crippled body parts.
# 
# 0 = Show every body part
# 1 = Show crippled body parts only
bShowOnlyCrippledBodyParts = 0

# Customize display of body part options in triage menu.
# Note that textual health description is shown on treatment menu as well.
# 
# 0 = Hide condition
# 1 = Description
# 2 = Percentage
# 3 = Description and percentage
#
# Default: 2
iShowBodyPartHealth = 2

# Emphasize crippled body-part conditions with asterisks.
#
# Default: 1
bShowBodyPartHealthEmphasis = 1

# Prefix body part options with skill requirements.
# Skill requirements may differ for body parts and their condition.
#
# 0 = Hide Medicine requirements (e.g. "Left Arm")
# 1 = Show required skill (e.g. "[Medicine 40] Left Arm")
# 2 = Show current and required skill (e.g. "[Medicine 35/40] Left Arm")
#
# Default: 1
iShowSkillRequirements = 1


[TreatmentMenu]

# Prefix treatment option item requirements with number held and needed (typically only one).
#
# 0 = Hide numbers (e.g. "[Medical Brace]")
# 1 = Show numbers only when requirements are not met (e.g. "[Medical Brace 0/1]")
# 2 = Always show number needed and held (e.g. "[Medical Brace 6/1]")
#
# Default: 0
iShowItemCountRequirements = 0


[Treatment]

# Maximum limb condition restored through treatment at maximum Medicine skill.
# Restoration scales with items used, the type of treatment, and the player's skill.
#
# Default: 0.85
fMaxRestoreFactor = 0.85
